stages:
 - build

variables:
  VERSION: 0.1.7

build-go:
  image: golang:1.17
  stage: build
  only:
    - master
  script:
    - go build -o goscrobble cmd/goscrobble/*.go
  artifacts:
    expire_in: 1 week
    paths:
      - goscrobble
      - migrations
      - init
      - .env.example
