START TRANSACTION;

ALTER TABLE albums ADD COLUMN `mbid` VARCHAR(36) DEFAULT '';
ALTER TABLE artists ADD COLUMN `mbid` VARCHAR(36) DEFAULT '';
ALTER TABLE tracks ADD COLUMN `mbid` VARCHAR(36) DEFAULT '';

COMMIT;
